name-template: '🌟 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ 新功能'
    label: 'feature'
  - title: '🐛 Bug修复'
    label: 'bug'
  - title: '🚀 优化'
    labels:
      - 'perf'
      - 'refactor'
  - title: '🧰 维护相关'
    label: 'chore'
  - title: '📚 文档更新'
    label: 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
